// Dependency-free checks for the local preview's rendering/storage helpers.
const fs=require('node:fs');
const path=require('node:path');
const vm=require('node:vm');
const assert=require('node:assert/strict');
const root=path.resolve(__dirname,'..');
const source=fs.readFileSync(path.join(root,'app.js'),'utf8');
const boundary=source.indexOf("document.addEventListener('click'");
assert(boundary>0,'Expected application/event wiring boundary');
const store=new Map();
const context=vm.createContext({URL,console,setTimeout,clearTimeout,localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v)}});
vm.runInContext(source.slice(0,boundary),context);
const run=s=>vm.runInContext(s,context);
assert.equal(run('defaults.length'),7);
assert.equal(run('profiles().length'),7);
assert.equal(run("profiles()[0].name"),'AntBeacon');
assert.equal(run(`safeURL('javascript:alert(1)')`),'');
assert.equal(run(`safeURL('data:text/html,hello')`),'');
assert.equal(run(`safeURL('https://user:secret@example.com')`),'');
assert.equal(run(`safeURL('https://example.com')`),'https://example.com/');
assert.equal(run(`e('<img src=x onerror="bad">')`),'&lt;img src=x onerror=&quot;bad&quot;&gt;');
assert.equal(run(`cleanProfile({color:'not-a-palette'}).color`),'forest');
assert.equal(run(`cleanProfile({logo:'data:image/svg+xml;base64,AAA'}).logo`),'');
assert.equal(run(`cleanProfile({name:'x'.repeat(100)}).name.length`),60);
assert.equal(run(`cleanProfile({services:Array.from({length:20},()=>({name:'Example'}))}).services.length`),8);
assert.equal(run(`profileContent({...defaults[0],name:'<script>bad</script>'}).includes('<script>bad</script>')`),false);
run(`draft.name='Unsaved work';bookmarks.add('northstar-ai');persist()`);
assert.notEqual(JSON.parse(store.get('antseed-directory-v1')).draft.name,'Unsaved work','Bookmarking must not save an unsaved draft');
run('persist(true)');assert.equal(JSON.parse(store.get('antseed-directory-v1')).draft.name,'Unsaved work');
run('published=cleanProfile(draft);persist(true)');assert.equal(run('profiles().length'),8);
assert.equal(JSON.parse(store.get('antseed-directory-v1')).published.name,'Unsaved work');
assert.equal(run('sponsorFormats.length'),4);
assert(fs.readFileSync(path.join(root,'index.html'),'utf8').includes('https://antseedmarkets.com/'));
for(const asset of ['app.js','style.css','partners.css','hardcore.css'])assert(fs.existsSync(path.join(root,asset)));
console.log('Passed: example data, URL restrictions, escaped text, profile limits, image restrictions, draft isolation, local publication and local assets.');
