import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (file) => fs.readFileSync(path.join(root, file), 'utf8');
const app = read('src/App.jsx');
const header = read('src/components/Header.jsx');
const theme = read('src/theme.jsx');
const main = read('src/main.jsx');
const stake = read('src/components/StakeANTS.jsx');
const css = read('src/design.css');

assert.match(theme, /catch \{ return 'editorial'; \}/, 'Editorial is the safe default when storage is unavailable');
assert.match(theme, /localStorage.getItem\('antseedmarkets.uiStyle'\) === 'classical' \? 'terminal' : 'editorial'/, 'Old preferences migrate');
assert.match(theme, /document.documentElement.dataset.theme = theme/, 'Apply theme to body and portalled components');
assert.match(theme, /try \{ localStorage.setItem\(KEY, theme\); \} catch/, 'Storage restrictions must not crash the UI');
assert.match(theme, /addEventListener\('storage', sync\)/, 'Synchronise themes across tabs');
assert.match(theme, /<RainbowKitProvider locale="en-US" theme=\{walletTheme\}>/, 'Wallet dialogs follow the selected theme');
assert.match(main, /<ThemeProvider>/, 'Theme provider wraps the live app');
assert.match(app, /const uiStyle = 'v2'/, 'Both themes retain the same working v2 components');
assert.match(app, /data-theme=\{theme\}/, 'Dashboard exposes the theme');
assert.match(app, /<StakeANTS uiStyle=\{uiStyle\} \/>/, 'Preserve live marketplace component');
assert.doesNotMatch(app, /key=\{theme\}/, 'Theme changes must not remount transaction forms');
assert.match(header, /role="group" aria-label="Theme"/, 'Theme control has a group label');
assert.match(header, /<span>Theme<\/span>/, 'Visible centred theme label');
assert.match(header, /aria-pressed=\{theme === 'editorial'\}/, 'Editorial selection is accessible');
assert.match(header, /aria-pressed=\{theme === 'terminal'\}/, 'Terminal selection is accessible');
assert.match(header, /<ConnectButton/, 'Keep RainbowKit wallet connection, not a mock button');
const nav = read('src/lib/nav.js');
assert.match(header, /visiblePrimaryNav\(\)/, 'Header renders the visible primary tab list');
assert.match(nav, /tab: 'stake', hidden: false/, 'My Antseed is visible in the AntBeacon market layout');
assert.match(nav, /tab: 'providers', hidden: false/, 'Providers stays promoted for the approved homepage navigation');
assert.match(nav, /tab: 'market', hidden: false/, 'Marketplace stays promoted for the approved homepage navigation');
assert.match(nav, /tab: 'stake', hidden: false \},\n  \{ tab: 'providers', hidden: false \},\n  \{ tab: 'market', hidden: false \}/, 'Primary nav order mirrors markets.antbeacon.com');
for (const tab of ['discovery', 'leaderboard', 'portfolio', 'rewards']) {
  assert.match(nav, new RegExp(`tab: '${tab}', hidden: true`), `${tab} is temporarily hidden from primary nav`);
}
for (const component of ['AntseedV2Hero','AntseedV2Metrics','LantsV2Card','AntseedV2How']) assert.ok(stake.includes(`function ${component}`));
assert.match(css, /html\[data-theme="terminal"\]/, 'Terminal styles are scoped');
assert.match(css, /#f7f5ed/, 'Retain editorial paper');
assert.match(css, /#63e8d0/, 'Terminal uses mint accents');
assert.match(css, /prefers-reduced-motion/, 'Respect reduced motion');
assert.ok(fs.existsSync(path.join(root, 'public/antseed-v2-art.svg')));
