const listings=[
 {id:127,pool:'antseed-zh',amount:10,days:732,price:10,start:'Oct 1, 2026',end:'Sep 28, 2028'},
 {id:131,pool:'antseed-zh',amount:10,days:732,price:15,start:'Oct 1, 2026',end:'Sep 28, 2028'},
 {id:129,pool:'antseed-zh',amount:10,days:732,price:20,start:'Oct 1, 2026',end:'Sep 28, 2028'},
 {id:98,pool:'Apex Ant',amount:10,days:732,price:29.9,start:'Oct 1, 2026',end:'Sep 28, 2028'},
 {id:100,pool:'Venice.ai Proxy',amount:10,days:732,price:30.1,start:'Oct 1, 2026',end:'Sep 28, 2028'}
];
const results=document.querySelector('#results');const seller=document.querySelector('#seller');const principal=document.querySelector('#principal');const sort=document.querySelector('#sort');
function render(){let rows=listings.filter(x=>(!seller.value||x.pool===seller.value)&&(!principal.value||(principal.value==='50'?x.amount>=50:x.amount==+principal.value)));rows.sort((a,b)=>sort.value==='high'?b.price-a.price:sort.value==='id'?a.id-b.id:a.price-b.price);if(!rows.length){results.innerHTML='<div class="empty">No example positions match these filters.</div>';return}results.innerHTML=rows.map(x=>`<article class="card"><div class="card-top"><span class="number">lANTS / #${x.id}</span><span class="status">Pending start</span></div><div class="card-main"><div class="pool"><span class="pool-icon">a</span>${x.pool}<span>↗</span></div><div class="amount">${x.amount}<small>ANTS staked</small></div><div class="terms"><div><span>LOCKED</span>728 days</div><div><span>UNLOCKS</span>${x.end}</div></div></div><div class="card-bottom"><div class="price">$${x.price.toFixed(2)}<small>$${(x.price/x.amount).toFixed(2)} / ANTS</small></div><button class="position-button" data-position="${x.id}">View position <span>↗</span></button></div></article>`).join('');document.querySelectorAll('[data-position]').forEach(b=>b.onclick=()=>openModal('Position #'+b.dataset.position,'This is a design preview using illustrative listing data. The live position detail will show its seller, principal, lock terms, ownership and available marketplace actions.'))}
[seller,principal,sort].forEach(x=>x.addEventListener('change',render));render();
document.querySelectorAll('[data-tab]').forEach(button=>button.onclick=()=>{document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('selected',b===button));if(button.dataset.tab==='history'){results.innerHTML='<div class="empty">No transaction history is connected in this preview.</div>'}else{render()}});
document.querySelector('#grid').onclick=()=>{results.classList.remove('list');document.querySelector('#grid').classList.add('selected');document.querySelector('#list').classList.remove('selected')};document.querySelector('#list').onclick=()=>{results.classList.add('list');document.querySelector('#list').classList.add('selected');document.querySelector('#grid').classList.remove('selected')};
function openModal(title,body){document.querySelector('#modal-title').textContent=title;document.querySelector('#modal-body').innerHTML='<p>'+body+'</p>';document.querySelector('#modal').showModal()}document.querySelector('#close').onclick=()=>document.querySelector('#modal').close();document.querySelector('#dismiss').onclick=()=>document.querySelector('#modal').close();document.querySelector('#explain').onclick=()=>openModal('What is lANTS?','A lANTS NFT represents a locked ANTS position in a seller pool. It is a position with terms and a time horizon—not a claim that can be withdrawn instantly. Review the contract and listing details before signing any transaction.');document.querySelectorAll('[data-info]').forEach(b=>b.onclick=()=>openModal(b.dataset.info,'Wallet and live marketplace actions are intentionally disabled in this design preview.'));
