const isRewards=location.pathname.endsWith('rewards.html');
const title=isRewards?'Rewards':'Portfolio';
const row=(label,value)=>`<div class="data-row"><span>${label}</span><strong>${value}</strong></div>`;
const panel=(label,title,rows)=>`<article class="activity-panel"><p class="eyebrow">${label}</p><h2>${title}</h2>${rows.map(r=>row(...r)).join('')}</article>`;
const lookup=`<section class="lookup"><div><label for="address">Look up any address</label><p>No connection needed to explore a public wallet on the live site.</p></div><form id="lookup-form"><input id="address" aria-describedby="lookup-status" placeholder="Enter a wallet address · 0x…" autocomplete="off"><button class="primary">Search <span>↗</span></button></form><p id="lookup-status" role="status">Design preview only. No address lookup or wallet connection is performed.</p></section>`;
const stateBar=`<div class="preview-controls"><span><span class="dot"></span> ILLUSTRATIVE DATA · NOT A REAL WALLET</span><div><button class="selected" data-state="populated">Example view</button><button data-state="empty">Disconnected view</button></div></div>`;
const portfolio=`<section class="summary-grid"><article><span>LOCKED HOLDINGS</span><strong>120 <small>ANTS</small></strong><p>Across 3 example positions</p></article><article><span>BUYER SPEND</span><strong>$48.60</strong><p>USDC spent on AI services</p></article><article><span>PROVIDER EARNINGS</span><strong>$216.40</strong><p>USDC earned serving requests</p></article><article class="summary-note"><span>YOUR PLACE IN THE NETWORK</span><p>A buyer. A provider.<br><em>A little of both.</em></p></article></section><section class="activity-grid">${panel('01 / USING THE NETWORK','Buyer activity',[['Spent USDC','$48.60'],['Deposited USDC','$100.00'],['Withdrawn USDC','$10.00'],['Requests','1,248'],['Input tokens','2,840,000'],['Output tokens','684,000'],['Channels','12'],['Unique providers','4'],['First seen','04 Sep 2026'],['Last seen','28 Sep 2026']])}${panel('02 / SUPPORTING THE NETWORK','Provider activity',[['Agent ID','#42'],['Earned USDC','$216.40'],['Staked USDC','$50.00'],['Requests','5,620'],['Input tokens','8,420,000'],['Output tokens','2,140,000'],['Unique buyers','28'],['Channels','36'],['First seen','01 Sep 2026'],['Last seen','28 Sep 2026']])}</section><section class="holdings"><div class="section-heading"><div><p class="eyebrow">03 / YOUR LOCKED POSITIONS</p><h2>A position of your own.</h2></div><a class="text-button" href="index.html#market">Explore the marketplace ↗</a></div><div class="table-scroll"><table><thead><tr><th>POSITION</th><th>PROVIDER POOL</th><th>PRINCIPAL</th><th>TIME REMAINING</th><th>STATUS</th></tr></thead><tbody><tr><td>#127</td><td>Example pool A</td><td>10 ANTS</td><td>728 days</td><td><span class="status">Listed</span></td></tr><tr><td>#131</td><td>Example pool A</td><td>10 ANTS</td><td>728 days</td><td><span class="status">Unlisted</span></td></tr><tr><td>#208</td><td>Example pool B</td><td>100 ANTS</td><td>364 days</td><td><span class="status">Unlisted</span></td></tr></tbody></table></div><p class="market-note">Holdings are read-only here. Listing, splitting, merging and moving positions belong in the lANTS marketplace.</p></section>`;
function rewardTable(side){return `<section class="reward-section"><div class="section-heading"><div><p class="eyebrow">${side==='buyer'?'01 / USING AI':'02 / PROVIDING AI'}</p><h2>${side==='buyer'?'Buyer':'Provider'} usage rewards</h2></div><span class="muted">Illustrative epochs</span></div><div class="table-scroll"><table><thead><tr><th>EPOCH</th><th>USAGE POINTS</th><th>REWARD</th><th>STATUS</th><th>YOUR NEXT STEP</th></tr></thead><tbody>${[26,25,24].map((epoch,i)=>`<tr><td><span class="epoch">${epoch}</span></td><td>${[1240,980,760][i].toLocaleString()}</td><td>${side==='buyer'?[12.5,8,6.2][i]:[24,16,10.8][i]} ANTS</td><td><span class="status">${i===2?'Staked':'Unclaimed'}</span></td><td>${i===2?'<span class="muted">Added to a position</span>':`<div class="row-actions"><button class="outline-button" data-claim="${side}" data-epoch="${epoch}">Claim</button><button class="small-primary" data-stake="${side}" data-epoch="${epoch}">${side==='buyer'?'Stake':'Restake'} ↗</button></div>`}</td></tr>`).join('')}</tbody></table></div></section>`}
const rewards=`<section class="reward-intro"><div><p class="eyebrow">UNCLAIMED USAGE REWARDS · EXAMPLE</p><div class="reward-total">60.5 <span>ANTS</span></div><p>Recognised participation.<br>A choice about what comes next.</p></div><div class="reward-breakdown">${row('From buying AI services','20.5 ANTS')}${row('From providing AI services','40 ANTS')}<p>Example values for design review. Not claimable balances.</p></div></section><aside class="warning"><span>!</span><div><strong>Two paths. One important choice.</strong><p>The existing app warns that claiming ANTS to your wallet is irreversible: those tokens cannot later be transferred or staked into a provider pool. Review the choice before you claim.</p></div></aside>${rewardTable('buyer')}${rewardTable('provider')}<section class="reward-footnote"><p class="eyebrow">KEEP THE DISTINCTION CLEAR</p><p>Buyer rewards can be staked into a registered provider pool. Provider rewards restake into the provider’s own pool. These screens demonstrate the choices only—nothing is signed or submitted.</p></section>`;
document.querySelector('#page-content').innerHTML=`<section class="page-hero"><div><p class="eyebrow"><span class="dot"></span> ${isRewards?'PARTICIPATION, RECOGNISED':'YOUR ACTIVITY, IN ONE PLACE'}</p><h1>${isRewards?'Small contributions.<br><em>Something to show.</em>':'Your stake.<br><em>Your story.</em>'}</h1><p class="intro">${isRewards?'Explore your usage rewards, and choose your next step.<br>Claim to a wallet or build a locked position.':'Your activity as a buyer and provider,<br>and the locked ANTS positions you hold.'}</p></div><div class="page-stamp" aria-hidden="true"><span>FIELD NOTES</span><strong>${isRewards?'03':'02'}</strong><span>${title.toUpperCase()} / ANTSEED MARKETS</span></div></section>${lookup}${stateBar}<div id="populated">${isRewards?rewards:portfolio}</div><section id="disconnected" class="disconnected" hidden><span class="empty-symbol">↗</span><h2>${isRewards?'Your next chapter starts here.':'Every position has a story.'}</h2><p>Connect your wallet or look up an address on the live site to view ${isRewards?'usage rewards':'activity and holdings'}.</p><button class="primary" data-demo-connect>Preview wallet connection ↗</button><p class="market-note">This is the disconnected-state design. No wallet is required for this prototype.</p></section>`;
const modal=document.querySelector('#modal');
function showModal(title,html){document.querySelector('#modal-title').textContent=title;document.querySelector('#modal-body').innerHTML=html;modal.showModal()}
document.querySelector('#close').onclick=()=>modal.close();document.querySelector('#dismiss').onclick=()=>modal.close();
document.querySelectorAll('[data-state]').forEach(button=>button.onclick=()=>{const empty=button.dataset.state==='empty';document.querySelector('#populated').hidden=empty;document.querySelector('#disconnected').hidden=!empty;document.querySelectorAll('[data-state]').forEach(b=>{b.classList.toggle('selected',b===button);b.setAttribute('aria-pressed',String(b===button))})});
document.querySelector('#lookup-form').onsubmit=e=>{e.preventDefault();document.querySelector('#lookup-status').textContent='This is a design-only prototype. No lookup was performed; all displayed values remain illustrative.'};
document.querySelectorAll('[data-info],[data-demo-connect]').forEach(b=>b.onclick=()=>showModal('A preview, not a connection.','<p>No wallet connection is requested. This prototype demonstrates layout and interactions only.</p>'));
document.querySelectorAll('[data-claim]').forEach(b=>b.onclick=()=>showModal('Before you claim.',`<p class="eyebrow">${b.dataset.claim.toUpperCase()} REWARD / EXAMPLE EPOCH ${b.dataset.epoch}</p><div class="warning"><div><strong>This choice is permanent on the live app.</strong><p>Claimed ANTS cannot later be transferred or staked into a provider pool. Staking and claiming are alternative paths, not steps you can take one after the other.</p></div></div><p>Design preview only. No claim will be submitted.</p>`));
document.querySelectorAll('[data-stake]').forEach(b=>b.onclick=()=>{const provider=b.dataset.stake==='provider';showModal(provider?'Back into your pool.':'Give your rewards a position.',`<p>Example epoch ${b.dataset.epoch} · ${provider?'Provider restake':'Buyer stake'} preview</p><form id="stake-preview" class="stake-form">${provider?'<div class="data-row"><span>Destination</span><strong>Your own provider pool</strong></div>':'<label>Provider pool<select required><option value="">Choose an example pool</option><option>Example pool A</option><option>Example pool B</option></select></label>'}<label>Lock duration (epochs)<input type="number" min="1" max="104" value="104" required></label><p class="market-note">Illustrative range. The live app reads the permitted lock duration from its contracts.</p><button class="primary">Review example ↗</button><p id="stake-message" role="status"></p></form>`);document.querySelector('#stake-preview').onsubmit=e=>{e.preventDefault();document.querySelector('#stake-message').textContent='Example reviewed. No transaction has been created, signed or submitted.'}});
